# Generated by Django 4.0.3 on 2022-04-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auction_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMails',
            new_name='UserEmails',
        ),
    ]
