# Generated by Django 4.0.3 on 2022-04-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auction_app', '0003_userinformation_rename_user_id_useremails_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
