# Generated by Django 4.0.3 on 2022-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auction_app', '0006_rename_useremails_useremail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremail',
            name='user_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
