# Generated by Django 4.0.3 on 2022-04-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_auction_app', '0007_alter_useremail_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremail',
            name='user_id',
        ),
        migrations.AddField(
            model_name='useremail',
            name='UserId',
            field=models.AutoField(default=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='useremail',
            name='user_email',
            field=models.CharField(max_length=500),
        ),
    ]
