# Generated by Django 4.0.3 on 2022-04-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_auction_app', '0008_remove_useremail_user_id_useremail_userid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmail',
        ),
    ]
